[workspace]
resolver = "2"
members = [
  "crates/*",
  "examples/*",
]

exclude = ["tests"]

[workspace.package]
version = "0.4.1"
edition = "2021"
authors = ["Riccardo Mazzarini <me@noib3.dev>"]
rust-version = "1.62"
description = "Rust bindings to all things Neovim"
documentation = "https://docs.rs/nvim-oxi"
readme = "./README.md"
repository = "https://github.com/noib3/nvim-oxi"
license = "MIT"
keywords = ["bindings", "neovim", "nvim"]

[workspace.dependencies]
once_cell = "1.19"
oxi-api = { version = "0.4.1", path = "./crates/oxi-api" }
oxi-libuv = { version = "0.4.1", path = "./crates/oxi-libuv" }
oxi-luajit = { version = "0.4.1", path = "./crates/oxi-luajit" }
oxi-macros = { version = "0.4.1", path = "./crates/oxi-macros", features = ["module"] }
oxi-types = { version = "0.4.1", path = "./crates/oxi-types", features = ["serde"] }
thiserror = "1.0"
