[package]
name = "oxi-derive"
version = "0.1.0"
authors = ["Riccardo Mazzarini <riccardo.mazzarini@pm.me>"]
edition = "2021"
description = "Procedural macros for the nvim-oxi crate."

[lib]
proc-macro = true
