[package]
name = "luajit-bindings"
version = "0.2.0"
authors = ["Riccardo Mazzarini <riccardo.mazzarini@pm.me>"]
edition = "2021"
description = "Minimal Rust bindings to LuaJIT"
repository = "https://github.com/noib3/nvim-oxi"
license = "MIT"

[dependencies]
once_cell = "1.15"
thiserror = "1.0"
