[package]
name = "luajit-bindings"
version = "0.1.0"
authors = ["Riccardo Mazzarini <riccardo.mazzarini@pm.me>"]
edition = "2021"
description = "Minimal Rust bindings to LuaJIT."

[dependencies]
once_cell = "1.15"
thiserror = "1.0"
