[package]
name = "nvim-oxi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
derive_builder = "0.11"
libc = "0.2"
nvim-types = { path = "../nvim-types" }
once_cell = "1.12"
thiserror = "1.0"
