[package]
name = "mechanic"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
nvim-oxi = { path = "../../nvim-oxi" }
serde = { version = "1.0", features = ["derive"] }
