[package]
name = "libuv-bindings"
version = "0.1.0"
authors = ["Riccardo Mazzarini <riccardo.mazzarini@pm.me>"]
edition = "2021"

[dependencies]
libuv-sys2 = "1.44.2"
lua-bindings = { version = "0.1", path = "../lua-bindings" }
once_cell = "1.15"
thiserror = "1.0"
