[package]
name = "nvim-diagnostic"
version = "0.1.0"
authors = ["Riccardo Mazzarini <riccardo.mazzarini@pm.me>"]
edition = "2021"

[dependencies]
luajit-bindings = { version = "0.2.0", path = "../luajit-bindings" }
nvim-api = { version = "0.2.0", path = "../nvim-api" }
