name: Testing

on: [push, pull_request]

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install latest stable Rustc
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Run tests
        run: cargo test -vv
        working-directory: oxi-tests
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install latest stable Rustc
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Run tests
        run: cargo test -vv
        working-directory: oxi-tests
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install latest stable Rustc
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Run tests
        run: cargo test -vv
        working-directory: oxi-tests
