name: Testing

on: [push, pull_request]

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Neovim # nightly
        uses: rhysd/action-setup-vim@v1
        with:
            neovim: true
            # version: nightly
      - name: Install latest stable `rustc`
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Run unit tests
        run: cargo test
        working-directory: .
      - name: Build the `tests` crate
        run: cargo build --release
        working-directory: ./tests
      - name: Run integration tests
        run: cargo test
        working-directory: ./tests
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Neovim # nightly
        uses: rhysd/action-setup-vim@v1
        with:
            neovim: true
            # version: nightly
      - name: Install latest stable `rustc`
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Run unit tests
        run: cargo test
        working-directory: .
      - name: Build the `tests` crate
        run: cargo build --release
        working-directory: ./tests
      - name: Run integration tests
        run: cargo test
        working-directory: ./tests
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Neovim # nightly
        uses: rhysd/action-setup-vim@v1
        with:
            neovim: true
            # version: nightly
      - name: Install latest stable `rustc`
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Run unit tests
        run: cargo test
        working-directory: .
      - name: Build the `tests` crate
        run: cargo build --release
        working-directory: ./tests
      - name: Run integration tests
        run: cargo test
        working-directory: ./tests
